### ISSUE TITLE
[建议]是否能检测win当前主题

### ISSUE THREAD

**Issue by misaka10843** [BookerLiu/ShowSeconds#4]
![image](https://user-images.githubusercontent.com/69132853/181746899-91aed1d7-50e0-403c-b086-0703a44bfdba.png)
使用明亮主题时也是暗黑主题的颜色，感觉有点不协调，所以想问下是否能检测win主题并且更换颜色，或者支持自定义颜色？

**Comment by BookerLiu** [comment]
功能已经增加了,  下个版本会有
